server:
  port: 9400

eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9300/eureka,http://LagouCloudEurekaServerB:9301/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-cloud-config
  cloud:
    config:
      server:
        # git配置：uri，用户名，密码，分支，项目
        git:
          uri: https://gitee.com/kangzenian/lagou-config.git  # git地址
          username: kangzenian  # git用户名
          password: Kzn19981127   # git密码
          search-paths:   # 项目路径
            - lagou-config
      # 读取分支
      label: master
  rabbitmq:
    host: 192.168.10.128
    port: 5672
    username: kangzenian
    password: 123456

#暴露所有的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"