server:
  port: 9000

spring:
  application:
    name: lagou-cloud-gateway
    # 网关配置
  cloud:
    gateway:
      routes: # 配置路由
        - id: service-order-router  # 路由名称
          uri: lb://lagou-service-order   # 配置动态路由，从注册中心获取对应的实例
          predicates:   # 设置断言 当断言成功后，交给某一个微服务处理时使用的是转发
            - Path=/order/**
          filters:  # 设置过滤器
            # 表示去掉断言中的路径，
            # 如：访问的url: http://127.0.0.1:9000/order/order/findAll，则转发的url为：http://127.0.0.1:9000/order/findAll
            - StripPrefix=1
        - id: service-goods-router
          uri: lb://lagou-service-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9300/eureka,http://LagouCloudEurekaServerB:9301/eureka
  instance:
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@